-- Persisted AI-generated client-conversation question set for the Search
-- Brief. Shape is { sections: [{ id, label, questions: [{ id, text, source,
-- library_id? }] }] }. Generated by /api/search-brief/generate-questions
-- and re-loaded on subsequent opens of the slide-over.

ALTER TABLE searches ADD COLUMN IF NOT EXISTS generated_question_set JSONB;
